### ISSUE TITLE
Create multiple ComputeEnv and queues with slots

### ISSUE THREAD

**Issue by ChristianKniep** [qnib/disbatch#7]
To spread the load of incoming jobs each region should have different queues and compute environments.
```yaml
spot:
  # Defines how many spot instances to use per region, based on assumption
  c5a.24xlarge: 
    eu-west-1: 25
    eu-west-2: 20
  c5.24xlarge:
    eu-west-1: 25
    eu-west-2: 20
  c5n.24xlarge: 
    eu-west-1: 25
    eu-west-2: 20
  c5.18xlarge:
    eu-west-1: 50
    eu-west-2: 25
  c5n.18xlarge: 
    eu-west-1: 30
    eu-west-2: 25
compute:
   spot_x86_96vcpu:
      instances: [c5a.24xlarge, c5.24xlarge]
      type: spot
   od_intel_96vcpu:
      instances: [c5.24xlarge]
      type: on-demand
   spot_x86_72+vcpu:
      instances: [c5a.24xlarge, c5.24xlarge,c5.18xlarge, c5n.18xlarge]
      type: spot
```
